AWSTemplateFormatVersion: "2010-09-09"
Description:
  This script create the resources for the Lambda function deployment
Parameters:
  SourceBucketName:
    Type: String
    Description: Images put in this bucket will trigger the Lambda function
  DestinationBucketName:
    Type: String
    Description: Bucket name where will be stored the thumbnail
Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref DestinationBucketName
  ZappaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - "logs:*"
            Resource: "arn:aws:logs:*:*:*"
          - Effect: Allow
            Action:
            - "lambda:InvokeFunction"
            Resource: "*"
          - Effect: Allow
            Action:
            - "s3:*"
            Resource: "*"
      Path: /
      RoleName: SamResizerRole
Outputs:
  ZappaRoleArn:
    Value: !GetAtt ZappaRole.Arn
    Description: Arn of Zappa role

